### ISSUE TITLE
Does the website of this project plan to write API interfaces?

### ISSUE THREAD

**Issue by 1592363624** [ddiu8081/chatgpt-demo#281]
### Clear and concise description of the problem

因为官方的调用需要魔法，这个不需要，所以想调用这个网站的

### Suggested solution

因为官方的调用需要魔法，这个不需要，所以想调用这个网站的

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yzh990918** [comment]
All call the official API.

**Comment by zqq-nuli** [comment]
我正在尝试基于这个网站调用第三方接口 这个打字机效果真的太酷了

**Comment by 1592363624** [comment]
> All call the official API.

知道是官方的api，我的意思是说网站弄个接口，掉这个接口传入问题，返回答案，因为调用官方的需要VPN，但是用这个网站中转就不用VPN了

**Comment by zqq-nuli** [comment]
> > All call the official API.
> 
> 知道是官方的api，我的意思是说网站弄个接口，掉这个接口传入问题，返回答案，因为调用官方的需要VPN，但是用这个网站中转就不用VPN了

你自己购买一个国外服务器就可以解决这个问题 或者你调国内的其他镜像的api

**Comment by 1592363624** [comment]
> > > All call the official API.
> > 
> > 
> > 知道是官方的api，我的意思是说网站弄个接口，掉这个接口传入问题，返回答案，因为调用官方的需要VPN，但是用这个网站中转就不用VPN了
> 
> 你自己购买一个国外服务器就可以解决这个问题 或者你调国内的其他镜像的api

是可以挂梯子，但是这个部署的不是正好就不需要翻墙吗，所以可以利用看看

**Comment by ddy-ddy** [comment]
这个网站应该是用vercel部署的，没办法单独做一个后端的接口吧。
而且这个做一个接口供大家调用，服务器开销也大😂

**Comment by ddy-ddy** [comment]
> > > > All call the official API.
> > > 
> > > 
> > > 知道是官方的api，我的意思是说网站弄个接口，掉这个接口传入问题，返回答案，因为调用官方的需要VPN，但是用这个网站中转就不用VPN了
> > 
> > 
> > 你自己购买一个国外服务器就可以解决这个问题 或者你调国内的其他镜像的api
> 
> 是可以挂梯子，但是这个部署的不是正好就不需要翻墙吗，所以可以利用看看

这个网站应该是用vercel部署的，没办法单独做一个后端的接口吧。
而且这个做一个接口供大家调用，服务器开销也大😂

**Comment by 1592363624** [comment]
> > > > > 都调用官方 API。
> > > > 
> > > > 
> > > > 知道是官方的api，我的意思是说网站弄个接口，掉这个接口传入问题，返回答案，因为调用官方的需要VPN，但是用这个网站中转就不用VPN了
> > > 
> > > 
> > > 你自己购买一个国外服务器就可以解决这个问题 或者你调国内的其他镜像的api
> > 
> > 
> > 是可以挂梯子，但是这个部署的不是正好就不需要翻墙吗，所以可以利用看看
> 
> 这个网站应该是用vercel部署的，没办法单独做一个后端的接口吧。 而且这个做一个接口供大家调用，服务器开销也大😂

我是想自己调用  接入到机器人玩玩

**Comment by vaan89** [comment]
慎用吧...我的号已经被封了

**Comment by zqq-nuli** [comment]
> 慎用吧...我的号已经被封了

我已经被封禁很多个账号了，但是不是使用这个项目，是我的小程序，所以我已经在考虑怎么购买官方的服务了

**Comment by zqq-nuli** [comment]
> > > > > > 都调用官方 API。
> > > > > 
> > > > > 
> > > > > 知道是官方的api，我的意思是说网站弄个接口，掉这个接口传入问题，返回答案，因为调用官方的需要VPN，但是用这个网站中转就不用VPN了
> > > > 
> > > > 
> > > > 你自己购买一个国外服务器就可以解决这个问题 或者你调国内的其他镜像的api
> > > 
> > > 
> > > 是可以挂梯子，但是这个部署的不是正好就不需要翻墙吗，所以可以利用看看
> > 
> > 
> > 这个网站应该是用vercel部署的，没办法单独做一个后端的接口吧。 而且这个做一个接口供大家调用，服务器开销也大😂
> 
> 我是想自己调用 接入到机器人玩玩

你是不会自己写后端代码吗，我自己写了一套给我的小程序使用，用的是硅谷的服务器做的转发

**Comment by ddiu8081** [comment]
Reconsider in #378.
